#!/bin/bash
whiptail --title "Welcome to Sleepy Port!" --msgbox "Use -TAB- to change between different buttons, -SPACEBAR- for choosing options, -ARROW KEYS- for navigating, and -$

#!/bin/bash
IPTABLE=$(whiptail --title "Test Checklist Dialog" --radiolist \
"Selection of Commands Select One" 20 90 15 \
"blacklist_all" "" OFF \
"whitelist_all" "" OFF \
"blacklist_one_ipaddress" "" OFF \
"whitelist_one_port" "" OFF \
"blacklist_one_ipaddress_and_port_for_ipaddress_to_not_use" "" OFF \
"whitelist_one_ipaddress_and_port_for_one_ipaddress_to_use" "" OFF  3>&1 1>&2 2>&3)



exitstatus=$?
if [ $IPTABLE = 'blacklist_all' ]; then
    sudo iptables -P INPUT DROP && sudo iptables -P OUTPUT DROP
    whiptail --title "Blacklist_all" --msgbox "All ipaddresses blaklisted and blocked!" 10 60
fi

exitstatus=$?
if [ $IPTABLE = 'whitelist_all' ]; then
    sudo iptables -P OUTPUT ACCEPT && sudo iptables -P INPUT ACCEPT
    whiptail --title "whitelist_all" --msgbox "All ipaddresses whitelisted and accepted!" 10 60
fi

exitstatus=$?
if [ $IPTABLE = 'blacklist_one_ipaddress' ]; then
    PET=$(whiptail --title "Test Free-form Input Box" --inputbox "What is your pet's name?" 10 60 
    sudo iptables -A INPUT -s x.x.x.x -j DROP && sudo iptables -A OUTPUT -s x.x.x.x -j DROP

fi
